/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2018-03-24 18:15:21 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/gql_blog -t comments -t users -t followers -t posts -s public
 *
 */


export namespace commentsFields {
  export type id = number;
  export type user_id = number;
  export type post_id = number;
  export type title = string;
  export type body = string;

}

export interface comments {
  id: commentsFields.id;
  user_id: commentsFields.user_id;
  post_id: commentsFields.post_id;
  title: commentsFields.title;
  body: commentsFields.body;

}

export namespace usersFields {
  export type id = number;
  export type email = string;

}

export interface users {
  id: usersFields.id;
  email: usersFields.email;

}

export namespace followersFields {
  export type follower_id = number;
  export type followee_id = number;

}

export interface followers {
  follower_id: followersFields.follower_id;
  followee_id: followersFields.followee_id;

}

export namespace postsFields {
  export type id = number;
  export type user_id = number;
  export type title = string;
  export type body = string;

}

export interface posts {
  id: postsFields.id;
  user_id: postsFields.user_id;
  title: postsFields.title;
  body: postsFields.body;

}
